//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.CommomLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PLD_LIMITES
    {
        public int Id { get; set; }
        public int Ano { get; set; }
        public Nullable<decimal> PLD_Min { get; set; }
        public Nullable<decimal> PLD_MaxEst { get; set; }
        public Nullable<decimal> PLD_MaxHr { get; set; }
    }
}
