//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.CommomLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class Carga_Diaria
    {
        public int id { get; set; }
        public System.DateTime Data { get; set; }
        public int Hora { get; set; }
        public int Submercado { get; set; }
        public Nullable<decimal> Previsto { get; set; }
        public Nullable<decimal> Verificado { get; set; }
        public Nullable<decimal> Desvio { get; set; }
        public System.DateTime Data_Update { get; set; }
    }
}
