//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.CommomLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnaReg
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnaReg()
        {
            this.EnaDiaria = new HashSet<EnaDiaria>();
            this.EnaSemanal = new HashSet<EnaSemanal>();
        }
    
        public int id { get; set; }
        public System.DateTime dt_entrada { get; set; }
        public string tipo_rodada { get; set; }
        public int RV { get; set; }
        public int mês { get; set; }
        public int ano { get; set; }
        public string caminho { get; set; }
        public int oficial { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnaDiaria> EnaDiaria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnaSemanal> EnaSemanal { get; set; }
    }
}
