//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.CommomLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnaSemanal
    {
        public int id { get; set; }
        public int id_Ena { get; set; }
        public string tipo { get; set; }
        public string regiao { get; set; }
        public System.DateTime dataInicio { get; set; }
        public System.DateTime dataFim { get; set; }
        public decimal Ena { get; set; }
    
        public virtual EnaReg EnaReg { get; set; }
    }
}
