//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.CommomLibrary
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Resultados_CPASEntitiesPrevs : DbContext
    {
        public Resultados_CPASEntitiesPrevs()
            : base("name=Resultados_CPASEntitiesPrevs")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PrevsDados> PrevsDados { get; set; }
        public virtual DbSet<PrevsReg> PrevsReg { get; set; }
    }
}
