//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Compass.CommomLibrary
{
    using System;
    using System.Collections.Generic;
    
    public partial class PrevsDados
    {
        public int id { get; set; }
        public int id_prevs { get; set; }
        public int posto { get; set; }
        public int sem1 { get; set; }
        public int sem2 { get; set; }
        public int sem3 { get; set; }
        public int sem4 { get; set; }
        public int sem5 { get; set; }
        public int sem6 { get; set; }
    
        public virtual PrevsReg PrevsReg { get; set; }
    }
}
